//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWed.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamScore
    {
        public int ExamID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<double> FirstTPoint { get; set; }
        public Nullable<double> MidTPoint { get; set; }
        public Nullable<double> LastTPoint { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
