//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWed.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolWedEntities : DbContext,ISchoolEntitiesData
    {
        public SchoolWedEntities(string connectionString)
             : base(connectionString)
        {
        }
        void ISchoolEntitiesData.SaveChanges()
        {
            this.SaveChanges();
        }

        public void Remove()
        {
            this.Remove();
        }

        public void Find()
        {
            this.Find();
        }

        public void Modified()
        {
            this.Modified();
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassRoom> ClassRooms { get; set; }
        public virtual DbSet<ExamScore> ExamScores { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<AllTableinOne_Result> AllTableinOne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllTableinOne_Result>("AllTableinOne");
        }
    
        public virtual ObjectResult<Seachingbarforschool_Result> Seachingbarforschool(string studentName, string className, string subjectName, string roles4student)
        {
            var studentNameParameter = studentName != null ?
                new ObjectParameter("StudentName", studentName) :
                new ObjectParameter("StudentName", typeof(string));
    
            var classNameParameter = className != null ?
                new ObjectParameter("ClassName", className) :
                new ObjectParameter("ClassName", typeof(string));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var roles4studentParameter = roles4student != null ?
                new ObjectParameter("roles4student", roles4student) :
                new ObjectParameter("roles4student", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seachingbarforschool_Result>("Seachingbarforschool", studentNameParameter, classNameParameter, subjectNameParameter, roles4studentParameter);
        }
    
        public virtual ObjectResult<Top10Student_Result> Top10Student()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top10Student_Result>("Top10Student");
        }
    }
}
